# Generated by Django 5.0.7 on 2024-10-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=500)),
                ("valor_orcado", models.DecimalField(decimal_places=2, max_digits=6)),
                ("data_vencimento", models.DateField()),
                ("data_compra", models.DateField()),
                (
                    "tipo_lancamento",
                    models.CharField(
                        choices=[
                            ("RE", "Receita"),
                            ("DE", "Despesas Essenciais"),
                            ("NE", "Despesas Não Essenciais"),
                            ("IN", "Investimentos"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("SAL", "Salários"),
                            ("COM", "Comissões"),
                            ("ALU", "Aluguel"),
                            ("AGU", "Água"),
                            ("LUZ", "Luz"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "A pagar"), ("P", "Pago")], max_length=1
                    ),
                ),
            ],
        ),
    ]
